### ISSUE TITLE
Cannot find module '/nodeschnaps/node.js'

### ISSUE THREAD

**Issue by vkk1978** [killmag10/nodeschnaps#13]
I get the following error after following documentation and adding a script to the job as is from documentation.
2017/01/03 11:05:35 - JavaScript - ERROR (version 7.0.0.0-25, build 1 from 2016-11-05 15.35.36 by buildguy) : Couldn't compile javascript: org.mozilla.javascript.JavaScriptException: Error: Cannot find module '/nodeschnaps/node.js' (<cmd>#1(Function)#241)

My Script is 
new Function(
    org.apache.commons.io.FileUtils.readFileToString(
      new java.io.File('D:\\Learning\\Pentaho\\node_modules\\nodeschnaps\\loader.js')
    )
)();

NodeJS();

I noticed that loader.js is requiring nodejs as follows:
require('nodeschnaps/node.js');

So I also tried to resolve error by changing it to 'lib/nodeschnaps/node.js' and its absolute path.

**Comment by killmag10** [comment]
Hi vkk1978,

you must set the environment variable NODESCHNAPS_PATH to the lib folder of nodeschnaps.
Path separator is like in the other path variables "**:**"
Because nodeschnaps need to know his own location to load his own modules.

https://github.com/killmag10/nodeschnaps#user-content-nodeschnaps_path

Example: `/home/lars/Projects/OpenSource/kitchen-stove/bin/include/../../resource/javascript:/home/lars/Projects/OpenSource/kitchen-stove/bin/include/../../library/javascript/node_modules:/home/lars/Projects/OpenSource/kitchen-stove/bin/include/../../library/javascript/node_modules/nodeschnaps/lib`

Code example in kitchen-stove: https://github.com/killmag10/kitchen-stove/blob/master/bin/include/environment.sh#L32

I will document this more clearly.

**Comment by killmag10** [comment]
Documentation updated.

**Comment by tieoneease** [comment]
Is there a way to provide the path to the lib without specifying an environment variable? This makes it pretty hard to build tools on top of NodeSchnaps and have them be portable in build environments such as maven. Especially if the js modules folder is something that is generated as part of the build process.

**Comment by killmag10** [comment]
Hi @tieoneease,
NODESCHNAPS_PATH is inside java a java property.
I think it should be possible to set it with maven.

It is used here: https://github.com/killmag10/nodeschnaps/blob/0.10.0/loader.js#L37

Or what way would you prefer, to set the path?
